stages:
  property_data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
      - data/raw/f_original magicbricks cleaned 12022 data.csv
      - src/data/data_cleaning.py
    outs:
      - data/cleaned/property_cleaned.csv

  data_preparation:
    cmd: python src/data/data_preparation.py
    params:
      - Data_Preparation.test_size
      - Data_Preparation.random_state
    deps:
      - data/cleaned/property_cleaned.csv
      - src/data/data_preparation.py
    outs:
      - data/interim/train.csv
      - data/interim/test.csv

  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
      - data/interim/train.csv
      - data/interim/test.csv
      - src/features/data_preprocessing.py
    outs:
      - data/processed/train_trans.csv
      - data/processed/test_trans.csv
      - models/preprocessor.joblib

  # train:
  #   cmd: python src/models/train.py
  #   params:
  #     - Train.Random_Forest
  #     - Train.LightGBM
  #     - Train.XGBoost
  #   deps:
  #     - src/models/train.py
  #     - data/processed/train_trans.csv
  #   outs:
  #     - models/model.joblib
  #     - models/power_transformer.joblib
  #     - models/stacking_regressor.joblib

  # evaluation:
  #   cmd: python src/models/evaluation.py
  #   deps:
  #     - src/models/evaluation.py
  #     - data/processed/train_trans.csv
  #     - data/processed/test_trans.csv
  #     - models/model.joblib
  #   outs:
  #     - reports/run_information.json

  # register_model:
  #   cmd: python src/models/register_model.py
  #   deps:
  #     - src/models/register_model.py
  #     - reports/run_information.json
